### ISSUE TITLE
Using current date for importing scrobbles?

### ISSUE THREAD

**Issue by hans-juergen** [taurheim/scrobblify#3]
Hi, great new tool, very  useful for new Last.fm users who have a Spotify listening history! I wonder if you know Last.fm Scrubbler which is a free Windows desktop app for importing different files and formats to your Last.fm account, e.g. CSV files or iTunes and WMP databases:

https://github.com/coczero/Last.fm-Scrubbler-WPF

The developer uses the current date when importing scrobbles older than 14 days, so Last.fm will accept them. Maybe you could also implement this option in your tool, so Spotify users could import the whole 90 days of their listening history? See also this new thread about Scrobblify on Get Satisfaction:

https://getsatisfaction.com/lastfm/topics/import-spotify-history

By the way, the ZIP file from Spotify also contains all your saved playlists in JSON format (not only from the last 90 days) which would be a good source of importing "scrobbles" (or rather saved songs) from Spotify as well.

**Comment by taurheim** [comment]
Good idea! Technically you're not supposed to do this but I will add it as an option
